openapi: 3.0.3
info:
  title: Calculator API
  version: 1.0.0
  description: Minir√§knar API

paths:
  /calculate:
    post:
      summary: Calculate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './model.yaml#/CalculationRequest'
      responses:
        '200':
          description: Calculation result
          content:
            application/json:
              schema:
                $ref: './response.yaml#/CalculationResponse'
                example:
                  result: 8
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: './response.yaml#/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: './response.yaml#/ErrorResponseServer'