openapi: 3.0.3
info:
  title: Calculator API
  version: 1.0.0
  description: Minir√§knar API

servers:
  - url: https://api.example.com     
    description: Production server
  - url: http://localhost:5000        
    description: Local development server

paths:
  /calculate:
    post:
      summary: Calculate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculationRequest'
      responses:
        '200':
          description: Calculation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculationResponse'
              example:
                result: 8
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseServer'

components:
  schemas:
    CalculationRequest:
      type: object
      required:
        - a
        - b
        - operation
      properties:
        a:
          type: number
          example: 5
          description: First operand
          minimum: -1e10
          maximum: 1e10
        b:
          type: number
          example: 3
          description: Second operand
          minimum: -1e10
          maximum: 1e10

        operation:
          type: string
          enum: ["+", "-", "*", "/"]
          example: "+"
          description: Operator

   
    # CalculationResponse:
    #   type: object
    #   properties:
    #     result:
    #       type: number
    #       example: 8

    # ErrorResponse:
    #   type: object
    #   properties:
    #     message:
    #       type: string
    #       example: "Invalid input"

    # ErrorResponseServer:
    #   type: object
    #   properties:
    #     message:
    #       type: string
    #       example: "Server error"